name: Build Web

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Web Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install node_modules
        run: yarn install

      - name: Build Prod
        run: yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          # clean: true
