name: Build Web

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Web Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install node_modules
        run: yarn install

      - name: Build Prod
        run: yarn run deploy

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
